# Generated by Django 2.2 on 2021-07-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('negative_id', models.DecimalField(decimal_places=1, max_digits=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=255, unique=True)),
                ('last_positive_id', models.DecimalField(decimal_places=1, max_digits=1000, null=True)),
                ('last_negative_id', models.DecimalField(decimal_places=1, max_digits=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('positive_id', models.DecimalField(decimal_places=1, max_digits=1000, null=True)),
            ],
        ),
    ]
